# https://ansible-builder.readthedocs.io/
---
version: 3

build_arg_defaults:
  # add '--force-with-deps' if building from an EE that already contains
  # collections, such as ee-supported-rhel[89]
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '-vvv'

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest

dependencies:
  galaxy: requirements.yml
  python: python-requirements.txt

options:
  package_manager_path: /usr/bin/microdnf

# contains credentials for pulling collections
additional_build_files:
  - src: ansible.cfg
    dest: configs

additional_build_steps:
  prepend_galaxy:
    - ADD _build/configs/ansible.cfg /etc/ansible/ansible.cfg
    - ARG ANSIBLE_GALAXY_SERVER_CERTIFIED_TOKEN
    - ARG ANSIBLE_GALAXY_SERVER_VALIDATED_TOKEN

...
